### ISSUE TITLE
No item images

### ISSUE THREAD

**Issue by ChickenDipper1** [Jimmy208/qb-shops#1]
Unsure why but the item images don't seem to work for me, but they work fine with jim-shops.
Everything else works great and a brilliant script!

A long shot but any chance of re-adding the restock shop event so that shops can be stocked back up from qb-truckerjob?

Thanks.

**Comment by Jimmy208** [comment]
Check qb-menu you didn't setup correctly (client.lua:12 or script.js:30), wait till next update.
